# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_remove_imageclient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclient',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
